# -*- coding: utf-8 -*-
from odoo import api, fields, models, tools, _
from odoo.exceptions import UserError, ValidationError

class Library(models.Model):
    _name = "library"
    _description = "Library model"

    name = fields.Char('Tên sách', required=True)
    description = fields.Text('Mô tả sách')
    quantity = fields.Integer('Số lượng', default=1)
    genre = fields.Selection([
        ('a', 'Giáo trình'),
        ('b', 'Sách tham khảo'),
        ('c', 'Truyện'),
        ('d', 'Sách kỹ năng')
    ], string='Gender', default='a')
    author = fields.Char('Tác giả')
    dob = fields.Date('Ngày xuất bản', required=False)
   
    book_image = fields.Binary("book Image", attachment=True, help="Book Image")    
    owner_id = fields.Many2one('res.partner', string='Owner')
    product_ids = fields.Many2many(comodel_name='product.product', 
                                string="Related Products", 
                                relation='pet_product_rel',
                                column1='col_pet_id',
                                column2='col_product_id')